version: '2.1'

services:
  nginx_load_balancer:
    image: nginx
    container_name: my_nginx_load_balancer
    ports:
      - "8083:80"
    volumes:
      - ./nginx/nginx_load_balancer.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nginx1
      - nginx2
    restart: always

  nginx1:
    image: nginx
    container_name: my_nginx1
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - app2
    restart: always

  nginx2:
    image: nginx
    container_name: my_nginx2
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - app2
    restart: always

  app:
    container_name: my_project_app
    build: ./
    command: bash -c 'while !</dev/tcp/pgpool/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      #- database
      - pgpool
      - pgpool-1
      - redis_master
      - redis_slave
    restart: always
    env_file:
      - .env

  app2:
    container_name: my_project_app_2
    build: ./
    command: bash -c 'while !</dev/tcp/pgpool/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
    depends_on:
      - pgpool
      - pgpool-1
      - redis_master
      - redis_slave
    restart: always
    env_file:
      - .env

  pg-0:
    image: docker.io/bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-1,pg-0
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_USERNAME=${REPMGR_USERNAME}
      - REPMGR_PASSWORD=${REPMGR_PASSWORD}

  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_USERNAME=${REPMGR_USERNAME}
      - REPMGR_PASSWORD=${REPMGR_PASSWORD}

  redis_master:
    image: redis:latest
    ports:
      - "6379:6379"

  redis_slave:
    image: redis:latest
    ports:
      - "6380:6379"
    command: ["redis-server", "--slaveof", "redis_master", "6379"]

  pgpool:
    image: docker.io/bitnami/pgpool:4
    ports:
      - 5433:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=${PGPOOL_SR_CHECK_USER}
      - PGPOOL_SR_CHECK_PASSWORD=${PGPOOL_SR_CHECK_PASSWORD}
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=${PGPOOL_POSTGRES_USERNAME}
      - PGPOOL_POSTGRES_PASSWORD=${PGPOOL_POSTGRES_PASSWORD}
      - PGPOOL_ADMIN_USERNAME=${PGPOOL_ADMIN_USERNAME}
      - PGPOOL_ADMIN_PASSWORD=${PGPOOL_ADMIN_PASSWORD}
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_POSTGRES_CUSTOM_USERS=${PGPOOL_POSTGRES_CUSTOM_USERS}
      - PGPOOL_POSTGRES_CUSTOM_PASSWORDS=${PGPOOL_POSTGRES_CUSTOM_PASSWORDS}
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgpool-1:
    image: docker.io/bitnami/pgpool:4
    ports:
    - 5434:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=${PGPOOL_SR_CHECK_USER}
      - PGPOOL_SR_CHECK_PASSWORD=${PGPOOL_SR_CHECK_PASSWORD}
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=${PGPOOL_POSTGRES_USERNAME}
      - PGPOOL_POSTGRES_PASSWORD=${PGPOOL_POSTGRES_PASSWORD}
      - PGPOOL_ADMIN_USERNAME=${PGPOOL_ADMIN_USERNAME}
      - PGPOOL_ADMIN_PASSWORD=${PGPOOL_ADMIN_PASSWORD}
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_POSTGRES_CUSTOM_USERS=${PGPOOL_POSTGRES_CUSTOM_USERS}
      - PGPOOL_POSTGRES_CUSTOM_PASSWORDS=${PGPOOL_POSTGRES_CUSTOM_PASSWORDS}
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  #postgres_data:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
